import type {
  ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence,
} from './participationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondenceService';

/**
 * FASE 25.46
 *
 * Declaración explícita mínima del ámbito de futura determinación
 * de Compatibility para una ParticipantRoleCorrespondence(P,R)
 * previamente existente.
 *
 * El único fundamento interno inmediato es:
 *
 * ParticipantRoleCorrespondence.
 *
 * ParticipantRoleCorrespondence NO produce automáticamente
 * ParticipantRoleCompatibilityDeterminationScope.
 *
 * El Scope requiere una nueva invocación externa explícita.
 *
 * El Scope NO determina todavía:
 *
 * - compatible;
 * - incompatible;
 * - CompatibilityCriterion;
 * - CompatibilityEvaluation;
 * - CompatibilityResult.
 */
export type ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCompatibilityDeterminationScopeInput =
  {
    participationSemanticStructureParticipantId: string;
    participationSemanticStructureConstitutionElementId: string;
  };

/**
 * FASE 25.46
 *
 * Materialización explícita del hecho:
 *
 * ParticipantRoleCorrespondence(P,R)
 * +
 * explicit ParticipantRoleCompatibilityDeterminationScopeInput(P,E)
 * +
 * exact participant identity match
 * +
 * exact ConstitutionElement identity match
 * +
 * invocación explícita
 * ->
 * ParticipantRoleCompatibilityDeterminationScope(P,R)
 *
 * Conserva exactamente por identidad:
 *
 * - ParticipantRoleCorrespondence;
 * - ParticipantRoleCompatibilityDeterminationScopeInput;
 *
 * y sólo añade:
 *
 * - participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeType.
 *
 * El Scope NO constituye:
 *
 * - ParticipantRoleCompatibilityCriterion;
 * - ParticipantRoleCompatibilityEvaluation;
 * - ParticipantRoleCompatibilityResult;
 * - ParticipantRoleEligibility;
 * - ParticipantRoleAssignment;
 * - RoleOccupation;
 * - RoleFulfillment;
 * - Membership.
 */
export type ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCompatibilityDeterminationScope =
  {
    semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence:
      ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence;

    participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeInput:
      ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCompatibilityDeterminationScopeInput;

    participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeType:
      'explicit-evaluation-result-deliberative-influence-effect-directional-reference-axis-relation-semantic-evaluation-operation-operand-requirements-structure-constituent-relation-semantic-interpretation-participation-semantic-structure-participant-role-compatibility-criterion-content-structure-constituent-relation-semantic-interpretation-participation-semantic-structure-participant-role-compatibility-criterion-content-structure-participant-role-compatibility-determination-scope';
  };

/**
 * FASE 25.46
 *
 * Sitúa explícitamente la ParticipantRoleCorrespondence(P,R)
 * como objeto de una futura determinación de Compatibility.
 *
 * Se comprueba exclusivamente:
 *
 * 1. participantId exacto contra P encapsulado genealógicamente;
 * 2. ConstitutionElementId exacto contra E, portador de R.
 *
 * NO se vuelve a comprobar ParticipationSemanticStructurePresence S.
 * NO se inspecciona lexicalmente SemanticInterpretation.
 * NO se consulta Availability.
 * NO se determina compatible/incompatible.
 */
export function establishProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCompatibilityDeterminationScope(
  semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence:
    ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence,

  participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeInput:
    ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCompatibilityDeterminationScopeInput
): ProductiveKnowledgeRecommendationEvaluationResultDeliberativeInfluenceEffectDirectionalReferenceAxisRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCompatibilityDeterminationScope | null {

  const relationSemanticInterpretation =
    semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence
      .semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantSemanticRoleRelationSemanticInterpretation;

  const relationDefinition =
    relationSemanticInterpretation
      .semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantSemanticRoleRelationDefinition;

  const relationPresence =
    relationDefinition
      .semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantSemanticRoleRelationPresence;

  const participantId =
    relationPresence
      .participantRoleCompatibilityCriterionContentStructureParticipantPresence2541
      .participationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantPresenceInput
      .participationSemanticStructureParticipantId;

  const semanticRoleElementPresence =
    relationPresence
      .constitutionElementSemanticRoleDefinition2538
      .participantRoleCompatibilityCriterionContentStructureConstituentRelationParticipationSemanticStructureConstitutionElementSemanticRolePresence
      .participantRoleCompatibilityCriterionContentStructureConstituentRelationParticipationSemanticStructureConstitutionElementSemanticCharacterization
      .semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureConstitutionElementDefinition
      .semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureConstitutionElementPresence;

  const semanticRoleElementId =
    semanticRoleElementPresence
      .participationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureConstitutionElementPresenceInput
      .participationSemanticStructureConstitutionElementId;

  if (
    participantId !==
    participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeInput
      .participationSemanticStructureParticipantId
  ) {
    return null;
  }

  if (
    semanticRoleElementId !==
    participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeInput
      .participationSemanticStructureConstitutionElementId
  ) {
    return null;
  }

  return {
    semanticEvaluationOperationOperandRequirementsStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureConstituentRelationSemanticInterpretationParticipationSemanticStructureParticipantRoleCompatibilityCriterionContentStructureParticipantRoleCorrespondence,
    participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeInput,
    participationSemanticStructureParticipantRoleCompatibilityDeterminationScopeType:
      'explicit-evaluation-result-deliberative-influence-effect-directional-reference-axis-relation-semantic-evaluation-operation-operand-requirements-structure-constituent-relation-semantic-interpretation-participation-semantic-structure-participant-role-compatibility-criterion-content-structure-constituent-relation-semantic-interpretation-participation-semantic-structure-participant-role-compatibility-criterion-content-structure-participant-role-compatibility-determination-scope',
  };
}
